#! /bin/bash

# Script for building a release version of MoneyPenny (target is bin/moneypenny)


#Make a kernel link, if it does not exist
if [ ! -e "kernel" ]
 then ln -s ../hbci_cern21/src kernel
fi
#Make a kernellibs link, if it does not exist
#remove link to debug libs
if [ -e "kernellibs" ]
 then rm kernellibs
fi

ln -s ../hbci_cern21/release/src kernellibs

# Make links in data directory
cd data
#Make a link for HC_220, if it does not exist
if [ ! -e "HC_220.xml" ]
 then ln -s ../../hbci_cern21/xml_data/HC_220.xml HC_220.xml
fi
#Make a link for HC_300, if it does not exist
if [ ! -e "HC_300.xml" ]
 then ln -s ../../hbci_cern21/xml_data/HC_300.xml HC_300.xml
fi
#make a link for hbci_pintan.xml
if [ ! -e "hbci_pintan.xml" ]
 then ln -s ../../hbci_cern21/xml_data/hbci_pintan.xml hbci_pintan.xml
fi
#Make a link for readers.xml, if it does not exist
if [ ! -e "readers.xml" ]
 then ln -s ../../hbci_cern21/xml_data/readers.xml readers.xml
fi
#Make a link for HBCI_Cern_Message_defines
if [ ! -e "HBCI_Cern_Message_defines" ]
 then ln -s ../../hbci_cern21/src/global/HBCI_Cern_Message_defines HBCI_Cern_Message_defines
fi
cd ..

if [ -z $QTDIR ]
  then export QTDIR=/usr
fi

rm Makefile
$QTDIR/bin/qmake-qt4  "CONFIG+=release" moneypenny.pro
make -j4 $1
