#! /bin/bash

# Script for building a release version of MoneyPenny (target is bin/moneypenny) and installing it to
# /opt/moneypenny

#Make the kernel
cd ../hbci_cern21
if [ -d "debug" ]
  then rm -f -r debug
fi

./make_release

# Clean moneypenny
cd ../moneypenny21
make clean

#Make a kernel link, if it does not exist
if [ ! -e "kernel" ]
 then ln -s ../hbci_cern21/src kernel
fi
#Make a kernellibs link
#remove link to debug libs
rm kernellibs

ln -s ../hbci_cern21/release/src kernellibs

# Make links in data directory
cd data
#Make a link for HC_220, if it does not exist
if [ ! -e "HC_220.xml" ]
 then ln -s ../../hbci_cern21/xml_data/HC_220.xml HC_220.xml
fi
#Make a link for HC_300, if it does not exist
if [ ! -e "HC_300.xml" ]
 then ln -s ../../hbci_cern21/xml_data/HC_300.xml HC_300.xml
fi
#make a link for hbci_pintan.xml
if [ ! -e "hbci_pintan.xml" ]
 then ln -s ../../hbci_cern21/xml_data/hbci_pintan.xml hbci_pintan.xml
fi
#Make a link for readers.xml, if it does not exist
if [ ! -e "readers.xml" ]
 then ln -s ../../hbci_cern21/xml_data/readers.xml readers.xml
fi
#Make a link for HBCI_Cern_Message_defines
if [ ! -e "HBCI_Cern_Message_defines" ]
 then ln -s ../../hbci_cern21/src/global/HBCI_Cern_Message_defines HBCI_Cern_Message_defines
fi
cd ..

if [ -z $QTDIR ]
  then export QTDIR=/usr
fi

qmake  "CONFIG+=release live_cd" moneypenny2.pro
make -j4
make INSTALL_ROOT=/opt install
#make clean