#! /bin/bash

# Script for building a debug version of MoneyPenny (target is bin/moneypenny)
# Creates links to source and data files in hbci_cern2 and runs qmake and make

#Make a kernel link, if it does not exist
echo "Creating kernel links..."
if [ ! -e "kernel" ]
 then ln -s ../hbci_cern21/src kernel
fi
#Make a kernellibs link, if it does not exist
#remove link to release libs
if [ -e "kernellibs" ]
 then rm kernellibs
fi

if [ -e "../hbci_cern21/Debug" ]
 #kernel was compiled with Eclipse
 then ln -s ../hbci_cern21/Debug kernellibs
 #kernel was compiled with cmake
 else ln -s ../hbci_cern21/debug/src kernellibs
fi
# Make links in data directory
echo "Creating data links..."
cd data
#Make a link for everythingHBCI.xml, if it does not exist
if [ ! -e "everythingHBCI.xml" ]
 then ln -s ../../hbci_cern21/xml_data/everythingHBCI.xml everythingHBCI.xml
fi
#Make a link for HC_220, if it does not exist
if [ ! -e "HC_220.xml" ]
 then ln -s ../../hbci_cern21/xml_data/HC_220.xml HC_220.xml
fi
#Make a link for HC_300, if it does not exist
if [ ! -e "HC_300.xml" ]
 then ln -s ../../hbci_cern21/xml_data/HC_300.xml HC_300.xml
fi
#make a link for hbci_pintan.xml
if [ ! -e "hbci_pintan.xml" ]
 then ln -s ../../hbci_cern21/xml_data/hbci_pintan.xml hbci_pintan.xml
fi
#Make a link for readers.xml, if it does not exist
if [ ! -e "readers.xml" ]
 then ln -s ../../hbci_cern21/xml_data/readers.xml readers.xml
fi
#Make a link for HBCI_Cern_Message_defines
if [ ! -e "HBCI_Cern_Message_defines" ]
 then ln -s ../../hbci_cern21/src/global/HBCI_Cern_Message_defines HBCI_Cern_Message_defines
fi
#Make a link for certificates dir
if [ ! -e "certificates" ]
 then ln -s ../../hbci_cern21/certificates certificates
fi
#finished data dir, cd up again
cd ..



if [ -z $QTDIR ]
  then QTDIR="/usr"
  export QTDIR
fi
echo "Deleting old Makefile..."

rm Makefile
echo "Running qmake..."

qmake-qt4  "CONFIG+=debug" moneypenny.pro
echo "Running make..."

make -j4 $1
